const ActionTypes = {
    SETSOCKETSTATUS: "SETSOCKETSTATUS",
    BIDUPDATE: "BIDUPDATE",
    ASKUPDATE: "ASKUPDATE",
    BOOKSNAPSHOT: "BOOKSNAPSHOT",
    MAXBID: 'MAXBID',
    MAXASK: 'MAXASK',
    CHANGECHARTPROP: 'CHANGECHARTPROP',
    CHANGECOLUMNORDER: 'CHANGECOLUMNORDER',
    SETPRECISION: 'SETPRECISION',
    CLEARSNAPSHOT: 'CLEARSNAPSHOT'
}

export default ActionTypes;